surface_mapping = {
        'US Open': 'hard', 'Adelaide': 'hard', 'Auckland': 'hard', 'Hobart': 'hard', 'Australian Open': 'hard',
        'Lyon': 'clay', 'Hua Hin': 'hard', 'Abu Dhabi': 'hard', 'Cordoba': 'clay', 'Rotterdam': 'hard',
        'Doha': 'hard', 'Dubai': 'hard', 'Merida': 'hard', 'WTA Austin': 'hard', 'ATP Dubai': 'hard',
        'ATP Santiago': 'clay', 'WTA Indian Wells': 'hard', 'ATP Indian Wells': 'hard', 'WTA Miami': 'hard',
        'ATP Miami': 'hard', 'ATP Estoril': 'clay', 'WTA Bogota': 'clay', 'ATP Marrakech': 'clay',
        'WTA Charleston': 'clay', 'ATP Houston': 'clay', 'ATP Monte Carlo': 'clay',
        'WTA Billie Jean King Cup - Group I': 'various', 'WTA Billie Jean King Cup - World Group': 'various',
        'WTA Stuttgart': 'clay', 'ATP Munich': 'clay', 'ATP Barcelona': 'clay', 'ATP Banja Luka': 'clay',
        'WTA Madrid': 'clay', 'ATP Madrid': 'clay', 'WTA Rome': 'clay', 'ATP Rome': 'clay', 'WTA Rabat': 'clay',
        'ATP Lyon': 'clay', 'ATP Geneva': 'clay', 'WTA Strasbourg': 'clay', 'ATP Hertogenbosch': 'grass',
        'WTA Hertogenbosch': 'grass', 'WTA Nottingham': 'grass', 'WTA Billie Jean King Cup - Group III': 'various',
        'ATP Davis Cup - Group III': 'various', 'ATP Stuttgart': 'grass', 'WTA Berlin': 'grass', 'ATP Halle': 'grass',
        'WTA Birmingham': 'grass', 'ATP Eastbourne': 'grass', 'ATP Mallorca': 'grass', 'WTA Eastbourne': 'grass',
        'ATP Wimbledon': 'grass', 'WTA Bad Homburg': 'grass', 'WTA Wimbledon': 'grass', 'ATP Gstaad': 'clay',
        'WTA Palermo': 'clay', 'WTA Budapest': 'clay', 'ATP Newport': 'grass', 'ATP Bastad': 'clay',
        'WTA Warsaw': 'clay', 'ATP Hamburg': 'clay', 'WTA Hamburg': 'clay', 'ATP Atlanta': 'hard',
        'WTA Billie Jean King Cup - Group II': 'various', 'WTA Washington': 'hard', 'WTA Livesport Prague Open': 'hard',
        'ATP Kitzbuhel': 'clay', 'ATP Washington': 'hard', 'ATP Davis Cup - Group IV': 'various', 'WTA Montreal': 'hard',
        'ATP Toronto': 'hard', 'ATP Cincinnati': 'hard', 'WTA Cincinnati': 'hard', 'WTA Cleveland': 'hard',
        'ATP Winston-Salem': 'hard', 'WTA US Open': 'hard', 'ATP US Open': 'hard', 'WTA Osaka': 'hard',
        'WTA San Diego': 'hard', 'ATP Davis Cup - World Group': 'various', 'ATP Davis Cup - World Group I': 'various',
        'WTA Guadalajara': 'hard', 'ATP Davis Cup - World Group II': 'various', 'ATP Chengdu': 'hard',
        'WTA Ningbo': 'hard', 'ATP Zhuhai': 'hard', 'WTA Tokyo': 'hard', 'ATP Astana': 'hard',
        'ATP Asian Games': 'various', 'WTA Beijing': 'hard', 'ATP Beijing': 'hard', 'ATP Shanghai': 'hard',
        'WTA Zhengzhou': 'hard', 'WTA Seoul': 'hard', 'WTA Hong Kong': 'hard', 'ATP Tokyo': 'hard',
        'WTA Cluj-Napoca': 'hard', 'ATP Antwerp': 'hard', 'WTA Monastir': 'hard',
        'ATP Stockholm': 'hard', 'WTA Nanchang': 'hard', 'ATP Basel': 'hard', 'Zhuhai': 'hard',
        'ATP Vienna': 'hard', 'WTA Finals - Cancun': 'hard', 'ATP Paris': 'hard',
        'ATP Metz': 'hard', 'ATP Sofia': 'hard', 'ATP Finals - Turin': 'hard',
        'ATP Next Gen Finals - Jeddah': 'hard', 'WTA Auckland': 'hard', 'ATP United Cup': 'various',
        'WTA United Cup': 'various', 'ATP Brisbane': 'hard', 'WTA Brisbane': 'hard', 'ATP Hong Kong': 'hard',
        'WTA Hobart': 'hard', 'ATP Adelaide': 'hard', 'WTA Adelaide': 'hard', 'ATP Australian Open': 'hard',
        'WTA Australian Open': 'hard', 'ATP Auckland': 'hard', 'WTA Hua Hin': 'hard', 'ATP Montpellier': 'hard ',
        'WTA Linz': 'hard', 'ATP Cordoba': 'clay', 'WTA Abu Dhabi': 'hard', 'ATP Dallas': 'hard',
        'WTA Doha': 'hard', 'ATP Marseille': 'hard', 'ATP Delray Beach': 'hard', 'ATP Buenos Aires': 'clay',
        'ATP Rotterdam': 'hard', 'WTA Dubai': 'hard', 'ATP Rio de Janeiro': 'clay', 'ATP Doha': 'hard',
        'ATP Los Cabos': 'hard', 'ATP Acapulco': 'hard', 'WTA Rouen': 'hard', 'ATP Bucharest': 'clay',
        'WTA Bogota': 'clay', 'Australian Open': 'hard', 'WTA Charleston': 'clay', 'ATP Estoril': 'clay',
        'WTA French Open': 'clay', 'ATP French Open': 'clay'
    }